channel_sources:
- freecad/label/dev,conda-forge
channel_targets:
- freecad dev
c_stdlib_version:     # [osx]
  - '11.0'            # [osx and arm64]
  - '10.13'           # [osx and x86_64]
c_compiler:           # [win]
  - vs2022            # [win]
cxx_compiler:         # [win]
  - vs2022            # [win]
qt6_main:
  - '6.8'
